<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Блог</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<?php include __DIR__ . '/../../parts/menu.phtml';?>
<?php if (!empty($post)):?>
    <h2><?=$nameCategoryByIdPost?></h2>
    <div>
        <h3><?=htmlspecialchars($post['title'])?></h3>
        <b><?=htmlspecialchars($post['text'])?></b>
    </div>
    <?php else:?>
    <p>Нет поста</p>
<?php endif;?>
</body>
</html>
